# Generated by Django 5.2.4 on 2025-07-05 09:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان اضافه شدن')),
                ('srs_level', models.PositiveIntegerField(default=1, verbose_name='سطح SRS')),
                ('next_review_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='زمان مرور بعدی')),
            ],
            options={
                'verbose_name': 'لغت کاربر',
                'verbose_name_plural': 'لیست لغات کاربران',
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'شروع نشده'), ('in_progress', 'در حال یادگیری'), ('completed', 'تکمیل شده')], default='not_started', max_length=20)),
                ('score', models.PositiveIntegerField(default=0, verbose_name='امتیاز')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.lesson')),
            ],
        ),
    ]
