# Generated by Django 5.2.4 on 2025-07-22 06:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام دستاورد")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "icon_name",
                    models.CharField(
                        help_text="نام آیکونی که در فرانت\u200cاند استفاده می\u200cشود",
                        max_length=50,
                        verbose_name="نام آیکون",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="زمان اضافه شدن"
                    ),
                ),
                (
                    "learning_stage",
                    models.IntegerField(default=1, verbose_name="مرحله یادگیری"),
                ),
                (
                    "next_review_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان مرور بعدی"
                    ),
                ),
            ],
            options={
                "verbose_name": "لغت کاربر",
                "verbose_name_plural": "لغات کاربران",
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="progress.achievement",
                    ),
                ),
            ],
        ),
    ]
