# Generated by Django 5.2.4 on 2025-07-06 00:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userword',
            options={'verbose_name': 'لغت کاربر', 'verbose_name_plural': 'لغات کاربران'},
        ),
        migrations.RemoveField(
            model_name='userword',
            name='srs_level',
        ),
        migrations.AddField(
            model_name='userword',
            name='learning_stage',
            field=models.IntegerField(default=1, verbose_name='مرحله یادگیری'),
        ),
        migrations.AlterField(
            model_name='userword',
            name='next_review_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان مرور بعدی'),
        ),
        migrations.DeleteModel(
            name='LessonProgress',
        ),
    ]
