# Generated by Django 5.2.4 on 2025-07-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stardust_points',
            field=models.IntegerField(default=0, verbose_name='امتیاز گرد و غبار ستاره\u200cای'),
        ),
    ]
