# Generated by Django 5.2.4 on 2025-07-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_stardust_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True, verbose_name='آخرین روز فعالیت'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='streak',
            field=models.PositiveIntegerField(default=0, verbose_name='استریک روزانه'),
        ),
    ]
