# Generated by Django 5.2.4 on 2025-07-22 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان درس")),
                (
                    "lesson_number",
                    models.PositiveIntegerField(verbose_name="شماره درس"),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[(10, "دهم"), (11, "یازدهم"), (12, "دوازدهم")],
                        verbose_name="پایه تحصیلی",
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        default="book", max_length=50, verbose_name="نام آیکون"
                    ),
                ),
            ],
            options={
                "verbose_name": "درس",
                "verbose_name_plural": "درس\u200cها",
                "ordering": ["grade", "lesson_number"],
                "unique_together": {("lesson_number", "grade")},
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "english_word",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="لغت انگلیسی"
                    ),
                ),
                (
                    "persian_meaning",
                    models.CharField(max_length=255, verbose_name="معنی فارسی"),
                ),
                (
                    "phonetic",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="تلفظ نوشتاری",
                    ),
                ),
                (
                    "audio_pronunciation",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="pronunciations/",
                        verbose_name="فایل صوتی تلفظ",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="content.lesson",
                        verbose_name="درس مربوطه",
                    ),
                ),
            ],
            options={
                "verbose_name": "لغت",
                "verbose_name_plural": "لغات",
                "ordering": ["english_word"],
            },
        ),
        migrations.CreateModel(
            name="ExampleSentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence_text", models.TextField(verbose_name="متن جمله")),
                (
                    "audio_sentence",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="sentences/",
                        verbose_name="فایل صوتی جمله",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="content.word",
                        verbose_name="لغت مربوطه",
                    ),
                ),
            ],
            options={
                "verbose_name": "جمله مثال",
                "verbose_name_plural": "جملات مثال",
            },
        ),
    ]
