# Generated by Django 5.2.4 on 2025-07-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="icon_name",
            field=models.CharField(
                default="book", max_length=50, verbose_name="نام آیکون"
            ),
        ),
    ]
